import {
  chunkSizeForY,
  VIEW_MARGIN_TILES,
  PRELOAD_RADIUS_TILES,
  PRELOAD_MAX_PER_TICK,
  PRELOAD_TIME_MS,
  MAX_CHUNK_SIZE,
} from "../config";
import { Chunk, chunkKey } from "./Chunk";
import { WorldGen } from "./WorldGen";
import { TileId, isSolid } from "./Tile";
import { CHUNK_WORKER_SRC } from "./workerSource.generated";
import type { DeltaEntry } from "../net/Protocol";

function floorDiv(a: number, b: number): number {
  return Math.floor(a / b);
}

interface TileEdit {
  fg?: number;
  bg?: number;
}

// Player edits are stored by ABSOLUTE world-tile coordinate (independent of chunk size), grouped
// into fixed blocks so applying a chunk's edits only scans nearby blocks, not every edit.
const DELTA_BLOCK = 256;
const MAX_INFLIGHT = 32; // cap on outstanding background chunk requests to the worker

// Owns the set of resident chunks, streams them in/out around the camera, and is the single gateway
// for reading/writing tiles by absolute world-tile coordinates. Chunks are VARIABLE-sized by depth
// band (chunkSizeForY); a chunk is keyed by its world-tile origin. Because tile values are a pure
// function of world coordinates, chunk size never changes tile content, only batching. Player edits
// are stored as absolute-coordinate deltas so a chunk can unload and regenerate (at any size)
// without losing changes.
export class ChunkManager {
  private chunks = new Map<string, Chunk>();
  private deltas = new Map<string, Map<string, TileEdit>>(); // blockKey → ("tx,ty" → edit)
  private worldgen: WorldGen;
  private worker: Worker | null = null; // background generation (null = synchronous fallback)
  private pending = new Set<string>(); // chunk keys currently being generated by the worker

  constructor(worldgen: WorldGen) {
    this.worldgen = worldgen;
    this.setupWorker();
  }

  get gen(): WorldGen {
    return this.worldgen;
  }

  /** Spin up the generation worker; on any failure (no Worker, CSP block, error) stay synchronous. */
  private setupWorker(): void {
    this.worker = null;
    this.pending.clear();
    try {
      if (typeof Worker === "undefined" || typeof URL === "undefined" || typeof URL.createObjectURL !== "function") return;
      const url = URL.createObjectURL(new Blob([CHUNK_WORKER_SRC], { type: "text/javascript" }));
      const w = new Worker(url);
      w.onmessage = (e) => this.onWorkerChunk(e.data);
      w.onerror = () => { this.worker = null; this.pending.clear(); }; // give up → sync fallback
      w.postMessage({ type: "init", seed: this.worldgen.seed });
      this.worker = w;
    } catch {
      this.worker = null;
    }
  }

  private onWorkerChunk(data: any): void {
    if (!data || data.type !== "chunk") return;
    const key = chunkKey(data.x0, data.y0);
    this.pending.delete(key);
    if (this.chunks.has(key)) return; // a synchronous ensure beat the worker — keep that one
    const chunk = new Chunk(data.x0, data.y0, data.size, { fg: data.fg, bg: data.bg, liquid: data.liquid });
    this.applyDeltas(chunk);
    this.chunks.set(key, chunk);
  }

  /** Ask the worker to generate a chunk in the background (no-op if it's resident/pending/at cap). */
  private requestChunk(x0: number, y0: number, size: number): void {
    if (!this.worker) return;
    const key = chunkKey(x0, y0);
    if (this.chunks.has(key) || this.pending.has(key) || this.pending.size >= MAX_INFLIGHT) return;
    this.pending.add(key);
    this.worker.postMessage({ type: "gen", x0, y0, size });
  }

  /** Throw away everything and start a fresh world (used by the debug reseed key). */
  reseed(seed: number): void {
    this.worldgen = new WorldGen(seed);
    this.chunks.clear();
    this.deltas.clear();
    if (this.worker) this.worker.terminate();
    this.setupWorker();
  }

  loadedChunks(): IterableIterator<Chunk> {
    return this.chunks.values();
  }

  get loadedCount(): number {
    return this.chunks.size;
  }

  /** The chunk containing world tile (tileX,tileY), or undefined if not resident. */
  private chunkFor(tileX: number, tileY: number): Chunk | undefined {
    const size = chunkSizeForY(tileY);
    return this.chunks.get(chunkKey(floorDiv(tileX, size) * size, floorDiv(tileY, size) * size));
  }

  private ensureChunk(x0: number, y0: number, size: number): Chunk {
    const key = chunkKey(x0, y0);
    let chunk = this.chunks.get(key);
    if (chunk) return chunk;
    chunk = this.worldgen.generateChunkAt(x0, y0, size);
    this.applyDeltas(chunk);
    this.chunks.set(key, chunk);
    return chunk;
  }

  /** Ensure every chunk overlapping the tile rectangle is resident (walks bands top-to-bottom). */
  private ensureRegion(minX: number, minY: number, maxX: number, maxY: number): void {
    let ty = minY;
    while (ty <= maxY) {
      const size = chunkSizeForY(ty);
      const y0 = floorDiv(ty, size) * size;
      let tx = minX;
      while (tx <= maxX) {
        const x0 = floorDiv(tx, size) * size;
        this.ensureChunk(x0, y0, size);
        tx = x0 + size;
      }
      ty = y0 + size;
    }
  }

  /**
   * Stream chunks around the view. Tier 1: the view+margin is ensured synchronously so a frame never
   * renders an incomplete chunk (and teleport lands on a complete view). Tier 2: a larger preload
   * ring is filled in the background, nearest-first, bounded by a count cap and a time budget, so
   * chunks are ready before the player walks into them. Everything outside the ring is dropped.
   */
  update(minTileX: number, minTileY: number, maxTileX: number, maxTileY: number): void {
    // Tier 1 — must be ready to render this frame.
    this.ensureRegion(
      minTileX - VIEW_MARGIN_TILES, minTileY - VIEW_MARGIN_TILES,
      maxTileX + VIEW_MARGIN_TILES, maxTileY + VIEW_MARGIN_TILES,
    );

    // Tier 2 — background pre-generation of the surrounding ring.
    const pMinX = minTileX - PRELOAD_RADIUS_TILES, pMaxX = maxTileX + PRELOAD_RADIUS_TILES;
    const pMinY = minTileY - PRELOAD_RADIUS_TILES, pMaxY = maxTileY + PRELOAD_RADIUS_TILES;
    const cx = (minTileX + maxTileX) / 2, cy = (minTileY + maxTileY) / 2;
    const missing: { x0: number; y0: number; size: number; d2: number }[] = [];
    {
      let ty = pMinY;
      while (ty <= pMaxY) {
        const size = chunkSizeForY(ty);
        const y0 = floorDiv(ty, size) * size;
        let tx = pMinX;
        while (tx <= pMaxX) {
          const x0 = floorDiv(tx, size) * size;
          if (!this.chunks.has(chunkKey(x0, y0))) { // view+margin already ensured above, so skipped here
            const dx = x0 + size / 2 - cx, dy = y0 + size / 2 - cy;
            missing.push({ x0, y0, size, d2: dx * dx + dy * dy });
          }
          tx = x0 + size;
        }
        ty = y0 + size;
      }
    }
    if (missing.length > 0) {
      missing.sort((a, b) => a.d2 - b.d2);
      if (this.worker) {
        // Off-thread: queue nearest-first, capped by MAX_INFLIGHT. No main-thread generation cost.
        for (const m of missing) {
          if (this.pending.size >= MAX_INFLIGHT) break;
          this.requestChunk(m.x0, m.y0, m.size);
        }
      } else {
        // Fallback: generate on the main thread within a time budget (never blows the frame).
        const t0 = performance.now();
        const cap = Math.min(PRELOAD_MAX_PER_TICK, missing.length);
        for (let i = 0; i < cap; i++) {
          this.ensureChunk(missing[i].x0, missing[i].y0, missing[i].size);
          if (performance.now() - t0 > PRELOAD_TIME_MS) break;
        }
      }
    }

    // Unload chunks entirely outside the preload window (+ pad). Deltas are retained.
    const pad = MAX_CHUNK_SIZE;
    for (const [key, chunk] of this.chunks) {
      if (
        chunk.x0 + chunk.size <= pMinX - pad || chunk.x0 >= pMaxX + pad ||
        chunk.y0 + chunk.size <= pMinY - pad || chunk.y0 >= pMaxY + pad
      ) {
        this.chunks.delete(key);
      }
    }
  }

  // --- Tile access by absolute world-tile coordinates -----------------------

  getFg(tileX: number, tileY: number): number {
    const chunk = this.chunkFor(tileX, tileY);
    if (!chunk) return TileId.Air;
    return chunk.fg[(tileY - chunk.y0) * chunk.size + (tileX - chunk.x0)];
  }

  getBg(tileX: number, tileY: number): number {
    const chunk = this.chunkFor(tileX, tileY);
    if (!chunk) return TileId.Air;
    return chunk.bg[(tileY - chunk.y0) * chunk.size + (tileX - chunk.x0)];
  }

  isSolid(tileX: number, tileY: number): boolean {
    return isSolid(this.getFg(tileX, tileY));
  }

  // --- Liquids (dynamic; not persisted as deltas — re-seeded from worldgen on reload) ----------

  getLiquid(tileX: number, tileY: number): number {
    const chunk = this.chunkFor(tileX, tileY);
    if (!chunk) return 0;
    return chunk.liquid[(tileY - chunk.y0) * chunk.size + (tileX - chunk.x0)];
  }

  setLiquid(tileX: number, tileY: number, v: number): void {
    const chunk = this.chunkFor(tileX, tileY);
    if (!chunk) return;
    chunk.liquid[(tileY - chunk.y0) * chunk.size + (tileX - chunk.x0)] = v;
  }

  // --- Player edits (absolute-coordinate deltas) ----------------------------

  private deltaBlockKey(tileX: number, tileY: number): string {
    return floorDiv(tileX, DELTA_BLOCK) + "," + floorDiv(tileY, DELTA_BLOCK);
  }

  private recordDelta(tileX: number, tileY: number, patch: TileEdit): void {
    const bk = this.deltaBlockKey(tileX, tileY);
    let block = this.deltas.get(bk);
    if (!block) { block = new Map(); this.deltas.set(bk, block); }
    const tk = tileX + "," + tileY;
    const existing = block.get(tk);
    block.set(tk, existing ? { ...existing, ...patch } : patch);
  }

  /** Overlay any stored edits that fall inside a freshly generated chunk (by absolute coords). */
  private applyDeltas(chunk: Chunk): void {
    const { x0, y0, size } = chunk;
    for (let by = floorDiv(y0, DELTA_BLOCK); by <= floorDiv(y0 + size - 1, DELTA_BLOCK); by++) {
      for (let bx = floorDiv(x0, DELTA_BLOCK); bx <= floorDiv(x0 + size - 1, DELTA_BLOCK); bx++) {
        const block = this.deltas.get(bx + "," + by);
        if (!block) continue;
        for (const [tk, edit] of block) {
          const comma = tk.indexOf(",");
          const tx = Number(tk.slice(0, comma)), ty = Number(tk.slice(comma + 1));
          if (tx < x0 || tx >= x0 + size || ty < y0 || ty >= y0 + size) continue;
          const idx = (ty - y0) * size + (tx - x0);
          if (edit.fg !== undefined) chunk.fg[idx] = edit.fg;
          if (edit.bg !== undefined) chunk.bg[idx] = edit.bg;
        }
      }
    }
  }

  setFg(tileX: number, tileY: number, id: TileId): void {
    const size = chunkSizeForY(tileY);
    const chunk = this.ensureChunk(floorDiv(tileX, size) * size, floorDiv(tileY, size) * size, size);
    chunk.fg[(tileY - chunk.y0) * size + (tileX - chunk.x0)] = id;
    this.recordDelta(tileX, tileY, { fg: id });
  }

  setBg(tileX: number, tileY: number, id: TileId): void {
    const size = chunkSizeForY(tileY);
    const chunk = this.ensureChunk(floorDiv(tileX, size) * size, floorDiv(tileY, size) * size, size);
    chunk.bg[(tileY - chunk.y0) * size + (tileX - chunk.x0)] = id;
    this.recordDelta(tileX, tileY, { bg: id });
  }

  // --- Delta sync (multiplayer join) ----------------------------------------

  /** Serialize all player edits (absolute coords) so a joining peer can reproduce world state. */
  exportDeltas(): DeltaEntry[] {
    const out: DeltaEntry[] = [];
    for (const block of this.deltas.values()) {
      for (const [tk, edit] of block) {
        const comma = tk.indexOf(",");
        out.push({ tx: Number(tk.slice(0, comma)), ty: Number(tk.slice(comma + 1)), fg: edit.fg, bg: edit.bg });
      }
    }
    return out;
  }

  /** Apply a batch of edits received from the host (called before any chunks are streamed in). */
  importDeltas(entries: DeltaEntry[]): void {
    for (const e of entries) {
      const patch: TileEdit = {};
      if (e.fg !== undefined) patch.fg = e.fg;
      if (e.bg !== undefined) patch.bg = e.bg;
      this.recordDelta(e.tx, e.ty, patch);
      const chunk = this.chunkFor(e.tx, e.ty);
      if (chunk) {
        const idx = (e.ty - chunk.y0) * chunk.size + (e.tx - chunk.x0);
        if (patch.fg !== undefined) chunk.fg[idx] = patch.fg;
        if (patch.bg !== undefined) chunk.bg[idx] = patch.bg;
      }
    }
  }
}
