// Bundles the chunk-generation worker (src/world/ChunkWorker.ts) to a single minified IIFE string
// and writes it to src/world/workerSource.generated.ts, which both builds (Vite/Pages and the
// esbuild artifact) embed. At runtime the main thread turns this string into a blob Worker. Keeping
// it a committed string means neither build needs special worker handling, and it works under the
// artifact's strict CSP when blob workers are allowed (with a synchronous fallback when they're not).
//
//   node scripts/build-worker.mjs
import { build } from "esbuild";
import { writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");

const result = await build({
  entryPoints: [resolve(root, "src/world/ChunkWorker.ts")],
  bundle: true,
  format: "iife",
  minify: true,
  target: "es2022",
  write: false,
});
const code = result.outputFiles[0].text;

const out = resolve(root, "src/world/workerSource.generated.ts");
writeFileSync(
  out,
  `// AUTO-GENERATED by scripts/build-worker.mjs — do not edit by hand.\n` +
    `export const CHUNK_WORKER_SRC = ${JSON.stringify(code)};\n`,
  "utf8",
);
console.log(`wrote ${out} (${(code.length / 1024).toFixed(1)} kB worker bundle)`);
